plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testImplementation 'com.codeborne:selenide:6.19.1'
    testImplementation 'mysql:mysql-connector-java:8.0.33'
    testImplementation 'commons-dbutils:commons-dbutils:1.8.1'
    testImplementation 'org.slf4j:slf4j-simple:2.0.9'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()
    systemProperties = [
            'selenide.headless': 'false',
            'selenide.browser': 'chrome'
    ]
}
